# SPDX-License-Identifier: GPL-2.0-only

LINUXINCLUDE += \
		-I$(VRPC_ROOT)/include/uapi/

hfastrpc-objs := dsp/virtio_fastrpc.o \
		 dsp/fastrpc_rpmsg.o \
		 dsp/fastrpc_glinkpkt.o \
		 dsp/fastrpc_core.o \
		 dsp/fastrpc_ioctl.o \
		 dsp/fastrpc_mem.o \
		 dsp/fastrpc_vq.o \
		 dsp/fastrpc_sysfs.o

obj-$(CONFIG_HYBRID_FASTRPC) += hfastrpc.o
